(function() {

if( typeof window === 'undefined' ) {
  return;
}

window.addEventListener('load', function() {

var g=void 0,m=!0,o=null,q=!1;"."===location.hostname[location.hostname.length-1]&&(location.hostname=location.hostname.substr(0,location.hostname.length-1));var s;
(function(){function t(a){return 10>a?"0"+a:""+a}var w=document.createElement("div");w.style.cssText="background-color:rgba(150,255,150,.5)";if(-1!==window.navigator.userAgent.indexOf("MSIE")&&-1===w.style.backgroundColor.indexOf("rgba")&&-1===location.href.indexOf("passtest"))document.body.innerHTML="<style>*{font-size:20px !important;text-align:center}</style><div style='padding: 30px;'>You seem to use an old version of Internet Explorer.<br>Please upgrade to Internet Explorer 9.</div>",s=g;else{s=
{};document.getElementsByTagName&&(document.head=document.head||document.getElementsByTagName("head")[0],document.body=document.body||document.getElementsByTagName("body")[0],document.g=document.documentElement);Date.prototype.G=function(a){var c=this.getHours();a&&(c%=12,0==c&&(c=12));return t(c)};Date.prototype.H=function(){return t(this.getMinutes())};Date.prototype.add=function(a,c,b,e){e===g&&(e=0);e=this.getMilliseconds()+e;b=this.getSeconds()+b+e/1E3;c=this.getMinutes()+c+b/60;a=this.getHours()+
a+c/60;this.setHours(a%24,c%60,b%60,e%1E3);this.setUTCDate(this.getUTCDate()+a/24);return this};String.prototype.splice||(String.prototype.splice=function(a,c,b,e){s.assert(!e,"implement it");for(var e=[],d=0;d<this.length;d++)e.push(this[d]);b?e.splice(a,c,b):e.splice(a,c);a="";for(d=0;d<e.length;d++)a+=e[d];return a});s.indexOf=function(a,c){s.assert(a.constructor===NodeList||s.e().h&&a.constructor===Object,a,a.constructor);for(var b=0;b<a.length;b++)if(a[b]===c)return b;return-1};s.Ga=function(a){s.assert(a.constructor===
NodeList||s.e().h&&a.constructor===Object,a,a.constructor);for(var c=[],b=0;b<a.length;b++)c.push(a[b]);return c};Element.prototype.Q=Element.prototype.appendChild;Element.prototype.appendChild=function(a){if(!this.lastChild||this.lastChild!==a)return this.Q(a)};Element.prototype.o=function(){this.style.visibility="hidden"};Element.prototype.show=function(){this.style.visibility="inherit"};Element.prototype.a=function(a){return document.defaultView.getComputedStyle(this,o).getPropertyValue(a)};Element.prototype.X=
function(){this.style.display="none"};Element.prototype.display=function(){this.style.display=""};Element.prototype.K=function(){return"none"!==this.a("display")};Element.prototype.n=function(){var a=0,c=0,b=this;do a+=b.offsetLeft,c+=b.offsetTop;while(b=b.offsetParent);return{x:a,y:c}};Element.prototype.W=function(){var a=window.innerWidth,c=window.innerHeight;s.assert("TEXTAREA"!==this.tagName);s.assert(a&&c);var b=document.createElement(this.tagName);b.style.fontSize="100px";b.style.position="absolute";
b.style.display="inline-block";b.style.top="0";b.style.fontFamily=this.a("font-family");b.style.zIndex="-1";b.style.whiteSpace="nowrap";b.style.visibility="hidden";b.innerHTML=this.innerHTML;""===b.innerHTML&&(b.innerHTML="y");document.documentElement.appendChild(b);var e=parseInt(b.a("width"),10),d=parseInt(b.a("height"),10),e=Math.min(c/d,a/e);document.documentElement.removeChild(b);this.style.fontSize=Math.floor(100*e)+"px";s.assert("block"===this.a("display")||"inline-block"===this.a("display")||
"table-cell"===this.a("display"),"this.getStyle('display')=="+this.a("display"),1);this.o();s.assert(this.a("font-size")===this.style.fontSize);for(b=100;this.a("width")<a&&this.a("height")<c&&--b;)this.style.fontSize=parseInt(this.style.fontSize,10)+2+"px";for(;(this.a("width")>a||this.a("height")>c)&&--b;)this.style.fontSize=parseInt(this.style.fontSize,10)-1+"px";s.assert(0<b,"max===0");this.show()};s.Da=function(a,c){var b={I:function(){this.e=this.T(this.z);this.version=this.q(navigator.userAgent)||
this.q(navigator.appVersion)},T:function(a){for(var b=0;b<a.length;b++){var c=a[b].c,e=a[b].R;this.r=a[b].j||a[b].b;if(c){if(-1!=c.indexOf(a[b].d))return a[b].b}else if(e)return a[b].b}},q:function(a){var b=a.indexOf(this.r);return-1==b?g:parseFloat(a.substring(b+this.r.length+1))},z:[{c:navigator.userAgent,d:"Chrome",b:"Chrome"},{c:navigator.userAgent,d:"OmniWeb",j:"OmniWeb/",b:"OmniWeb"},{c:navigator.vendor,d:"Apple",b:"Safari",j:"Version"},{R:window.opera,b:"Opera"},{c:navigator.vendor,d:"iCab",
b:"iCab"},{c:navigator.vendor,d:"KDE",b:"Konqueror"},{c:navigator.userAgent,d:"Firefox",b:"Firefox"},{c:navigator.vendor,d:"Camino",b:"Camino"},{c:navigator.userAgent,d:"Netscape",b:"Netscape"},{c:navigator.userAgent,d:"MSIE",b:"Explorer",j:"MSIE"},{c:navigator.userAgent,d:"Gecko",b:"Mozilla",j:"rv"},{c:navigator.userAgent,d:"Mozilla",b:"Netscape",j:"Mozilla"}],ca:[{c:navigator.platform,d:"Win",b:"Windows"},{c:navigator.platform,d:"Mac",b:"Mac"},{c:navigator.userAgent,d:"iPhone",b:"iPhone/iPod"},
{c:navigator.platform,d:"Linux",b:"Linux"}]};b.I();var e="<div style='padding: 30px'>",d="in order to use "+a+' download the latest version of your browser at <a target="_blank" href=';if(b.e){var f=b.e;"Chrome"===f?(f="Google Chrome",d+="'http://www.google.com/chrome/'>www.google.com/chrome</a>"):"Firefox"===f?d+="'http://www.mozilla.com/firefox/'>www.mozilla.com/firefox</a>":"Safari"===f?d+="'http://www.apple.com/safari/download/'>www.apple.com/safari/download</a>":"Explorer"===f?(f="Internet Explorer",
d="in order to use "+a+" install the Google Chrome Frame plug-in at <a target='_blank' href='http://code.google.com/chrome/chromeframe/'>http://code.google.com/chrome/chromeframe</a>"):d=o;e+="you are using the browser "+f;b.version&&(e+=" "+b.version);e+="<br><br>";d&&(e+=d+".<br><br>")}e+=a+" supports following browsers:<br>     <ul>       <li><b>Internet Explorer</b> with the <b>Google Chrome Frame</b> plug-in</li>       <li><b>Firefox 3.5</b> or higher</li>       <li><b>Safari 5</b> or higher</li>       <li><b>Google Chrome 4</b> or higher</li>     </ul>     ";
c&&(e+="<br>"+c);document.body.innerHTML=e+"</div>"};window.console&&(console.print=function(a){console.log(JSON.stringify(a))},console.ya=function(){console&&console.log&&console.log(Error().stack)});s.assert=function(a,c,b,e){if(!a){var d;b||(b=0);b++;d=Error().stack;s.e().h&&console&&console.log&&console.log(d);if(d){d=d.toString().replace(/.*[\s\S]/,"");do d=d.replace(/.*[\s\S]/,"");while(b--);d=/[^\/]*$/.exec(d.split("\n")[0]).toString().replace(/\:[^\:]*$/,"")}d="assertion fail at "+d;c!==g&&
(d+=": "+c);if(e)throw d;var f="localhost"===window.location.hostname;if(-1===window.navigator.userAgent.indexOf("MSIE")){console&&console.log&&!f&&console.log(d);for(var h=3;h<arguments.length;h++)console&&console.log?console.log(arguments[h]):d+=arguments[h]+"\n";f&&window.alert(d);if(f)throw d;}}};var x,v=[];s.u=function(a){v.push(a);x||(x=window.setInterval(function(){for(var a in v)v[a]()},150))};s.hash={};s.hash.get=function(){var a=location.hash.substring(1);s.e().L&&(a=a.replace(/%23/g,"#"));
return a};s.hash.set=function(a){a[0]&&"#"===a[0]&&(a="#"+a);location.hash=a};s.hash.pa=function(){return""===s.hash.get()};s.hash.clear=function(){0===scrollY&&0===scrollX?location.hash="#":(this.M||(s.m(function(){var a=s.hash.get();if("##"===a||"%23%23"===a)a=[scrollX,scrollY],location.hash="#",scrollTo(a[0],a[1])}),this.M=m),location.hash="###")};s.m=function(a){if(window.onhashchange!==g)window.addEventListener("hashchange",function(){a()},q);else{var c=location.hash;s.u(function(){location.hash!=
c&&(c=location.hash,a())})}};s.ia=function(a){if(a.i)return a.i;if(window.event)return a.keyCode;if(a.which)return a.which;if(a.keyCode)return a.keyCode};s.J=function(a){return a.ctrlKey||a.altKey||a.metaKey};var p;s.v=function(a){var c=s.e().h;if(!p||c){for(var c=document.getElementsByTagName("link"),b=0;b<c.length;b++)"icon"==c[b].getAttribute("rel").toLowerCase()&&document.head.removeChild(c[b]);p=document.createElement("link");p.rel="icon";p.type="image/png";document.head.appendChild(p)}p.href=
a};s.aa=function(a){var c=document.createElement("canvas");c.height=32;c.width=32;var b=c.getContext("2d");a(b);s.v(c.toDataURL())};s.Ea=function(a,c,b){a||(a=1);c||(c="black");var e=new Date,d=document.createElement("canvas");d.height=32/a;d.width=32/a;var f=d.getContext("2d");f.fillStyle=c;f.font=Math.floor(15/a)+"pt arial";f.fillText(e.G(b),0,s.e().h?15/a:14/a);f.font=16/a+"pt arial";f.fillText(e.H(),5/a,32/a);return d.toDataURL()};s.ea=function(a,c,b){var e=document.createElement("canvas"),d=
e.getContext("2d");e.height=a;e.width=a;d.clearRect(0,0,a,a);var f=d.createLinearGradient(0,0,0,a);f.addColorStop(0,b);f.addColorStop(1,c);d.fillStyle=f;d.beginPath();var h=[a/20,-a/4],c=[0,a/2],b=[a/10,a/2],f=[a/4,a-a/4],i=[a-a/10,0],l=[a,0],k=[a,a/10],n=[a/4,a],j=[n[0]+h[0]+a/10,n[1]+h[1]-a/10],r=[0,a/2+a/10],p=[n[0]-a/10,n[1]-a/10],p=[p[0]+a/40,p[1]-a/40],a=[f[0]+h[0],f[1]+h[1]];d.moveTo(c[0],c[1]);d.lineTo(b[0],b[1]);d.lineTo(f[0],f[1]);d.lineTo(p[0],p[1]);d.quadraticCurveTo(a[0],a[1],i[0],i[1]);
d.lineTo(l[0],l[1]);d.lineTo(k[0],k[1]);d.quadraticCurveTo(j[0],j[1],n[0],n[1]);d.lineTo(n[0],n[1]);d.lineTo(r[0],r[1]);d.lineTo(c[0],c[1]);d.fill();return e.toDataURL()};(function(){var a;(function(){var c={};a=function(a,e){if(!c[a]){var d=document.createElement("canvas");d.height=32/e;d.width=32/e;var f=d.getContext("2d");f.scale(1/e,1/e);f.fillStyle=a;f.fillRect(0,0,300,150);c[a]=d.toDataURL()}return c[a]}})();s.Fa=function(c,b,e,d){e||(e=1);if(d)return a(d,e);if(0>=c&&b)return a(0===Math.abs(c)%
2?"red":"transparent",e);d=document.createElement("canvas");d.height=32/e;d.width=32/e;var f=d.getContext("2d"),h=c/60|0,i=99<h;i&&(h%=60);var l=i?c/3600|0:h,c=i?h:c%60;if(b!==g&&b!==o){s.assert(1>=b&&0<=b,"percent==="+b);h=d.height;i=d.width;f.fillStyle="#0f0";f.fillRect(0,0,i,h);f.moveTo(i/2,0);var k=(2*h+2*i)*b;k<=i/2?k=[i/2+k,0]:(f.lineTo(i,0),k<=i/2+h?k=[i,k-i/2]:(f.lineTo(i,h),k<=i/2+h+i?k=[i-(k-i/2-h),h]:(f.lineTo(0,h),k<=i/2+h+i+h?k=[0,h-(k-i/2-h-i)]:(s.assert(k<=i/2+h+i+h+i/2,b),f.lineTo(0,
0),k=[k-(i/2+h+i+h),0]))));f.lineTo(k[0],k[1]);f.lineTo(i/2,h/2);f.fillStyle="#faa";f.fill()}else f.fillStyle="#55F",f.fillRect(0,0,f.canvas.height,f.canvas.width);f.scale(1/e,1/e);f.fillStyle=b===g||b===o?"white":"black";0<l?(f.font="15pt arial",f.fillText(t(l),0,s.e().h?15:14),f.font="16pt arial",f.fillText(t(c),5,32)):(f.font="20pt arial",f.textAlign="center",f.fillText(c,16+(e&&1===c.length?1:0),25));return d.toDataURL()}})();s.ba=function(a,c,b){var e=document.createElement("canvas"),d=e.getContext("2d");
e.height=c;e.width=c;b||(b=[-4,0]);var f=4<a.length?c/3:1==a.length?c:c/2,h=(c-1)/2,i=(c-1)/2,c=c/2-f/2,l;for(l in a){var k=2*Math.PI*l/a.length;d.drawImage(a[l],Math.cos(k)*c-f/2+h+b[0],Math.sin(k)*c-f/2+i+b[1],f,f)}return e.toDataURL()};s.fa=function(a,c){function b(){var a,b;if(0===d.length)a=e[0][0];else{var c=Math.floor(Math.random()*d.length);a=d[c][0];b=d[c][1];d.splice(c,1)}b||(b=[parseInt(a[0]+(255-a[0])/2,10),parseInt(a[1]+(255-a[1])/2,10),parseInt(a[2]+(255-a[2])/2,10)]);return["rgb("+
a[0]+","+a[1]+","+a[2]+")","rgb("+b[0]+","+b[1]+","+b[2]+")"]}var e=[[[71,183,230],[181,226,245]],[[43,171,51]],[[250,27,228]],[[29,189,207]],[[191,82,255]],[[174,82,255]],[[223,45,0]],[[237,85,85]]];a&&(e=[[[100,100,100]]]);var d=e.slice();if(c){for(var f=[];c--;)f.push(b());return f}return b()};s.Ja=function(a,c,b){var e=arguments.callee,d=new XMLHttpRequest;d.onreadystatechange=function(){4==d.readyState&&(b&&b(d.responseText),e.k--,e.p&&0===e.k&&(e.p(),delete e.p))};var f="GET";"GET"==c?c=o:c&&
(f="POST",d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"));d.open(f,a,m);d.send(c);e.k||(e.k=0);e.k++};s.ka=function(){for(var a=[],c,b=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),e=0;e<b.length;e++)c=b[e].split("="),a.push(c[0]),a[c[0]]=window.decodeURIComponent(c[1]);return a};s.da=function(){for(var a=document.cookie.split(";"),c=0;c<a.length;c++){var b=a[c].indexOf("=");document.cookie=(-1<b?a[c].substr(0,b):a[c])+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT"}};
s.wa=function(a,c){var b=document.createElement("script");b.src=a;c&&(b.onload=c);document.getElementsByTagName("head")[0].appendChild(b)};s.va=function(a){var c=document.createElement("link");c.setAttribute("rel","stylesheet");c.setAttribute("type","text/css");c.setAttribute("href",a);document.getElementsByTagName("head")[0].appendChild(c)};(function(){var a={};s.Z=function(c,b){if(!b||!a[c]){var e=document.createElement("style");e.appendChild(document.createTextNode(c));e.setAttribute("type","text/css");
document.getElementsByTagName("head")[0].appendChild(e);b&&(a[c]=m)}}})();var j=o;s.e=function(){if(!j){j={};var a=window.navigator.userAgent.toLowerCase();-1<a.indexOf("googlebot")||-1<a.indexOf("msnbot")||-1<a.indexOf("slurp")?j.na=m:-1<a.indexOf("webkit")?j.Ia=m:-1<a.indexOf("gecko")&&(j.h=m);!/\bchrome\b/.test(a)&&/safari/.test(a)&&(j.L=m);/Mac/.test(navigator.platform)&&(j.qa=m);/Win/.test(navigator.platform)&&(j.sa=m);window.opera&&(j.ra=m)}return j};s.ua=function(a){a=a.replace(/(^|\s)((https?\:\/\/)[^\s@]+\.[^\s@]+)(?=$|\s)/g,
'$1<a href="$2" target="_blank">$2</a>');a=a.replace(/(^|\s)((?:www\.)?(?:[a-zA-Z\-]+\.)+(?:com|de|fr|uk|us|es|org|net|im)(?:(?:\/|#)[^\s@]*)?)(?=$|\s)/g,'$1<a href="http://$2" target="_blank">$2</a>');return a=a.replace(/(^|\s)([a-zA-Z\-\.]+@[a-zA-Z\-\.]+\.[a-zA-Z\-\.]+)(?=$|\s)/g,'$1<a href="mailto:$2" target="_blank">$2</a>')};s.ga=function(a){return a.replace(/((<)|(>)|(&))/g,function(a,b,e,d,f){if(e)return"&lt;";if(d)return"&gt;";if(f)return"&amp;"})};s.Ba=function(a,c){function b(){var a=l++;
f.clearRect(0,0,d,e);f.beginPath();a/=6*Math.PI;f.arc(d/2,e/2,d/2-i/2,0-Math.PI/4+a,Math.PI/2+a,q);f.stroke();setTimeout(b,10)}s.assert(a&&a.getContext("2d"));var e=parseInt(a.a("height"),10)||parseInt(a.style.height,10)||a.height,d=parseInt(a.a("width"),10)||parseInt(a.style.width,10)||a.width;s.assert(d&&e&&d===e,"! width===height");a.height=e;a.width=d;var f=a.getContext("2d"),h=f.createLinearGradient(0,0,d,e);h.addColorStop(0,c?c:"#888");h.addColorStop(1,c?c:"#555");f.strokeStyle=h;var i=d/8;
f.lineWidth=i;var l=0;b()};var r;s.ja=function(a){function c(){if(b){document.g.removeChild(b);document.g.appendChild(b);s.assert(b);b.style.top="";b.style.bottom="";b.style.marginLeft="";b.style.width="";b.style.left="";b.style.overflowY="";var a=parseInt(b.a("width"));b.style.width=a+"px";b.style.marginLeft=-a/2+"px";var c=parseInt(b.a("height"),10),a=parseInt(b.n().y)-scrollY,c=parseInt(innerHeight)-a-c,e=a+c;0>e?(b.style.top="0",b.style.display="absolute"):a>c&&(b.style.top="auto",b.style.bottom=
parseInt(e/2,10)-parseInt(b.a("margin-bottom"))+"px");b.style.overflowY="auto";b.style.left="50%"}}if(r)return r.U(a),r;r={};var b,e,d,f;r.close=function(){var a=q;document.g.classList.remove("popup");if(b)try{document.g.removeChild(b),a=m}catch(c){}if(e)try{document.g.removeChild(e)}catch(l){}b=g;window.clearInterval(d);d=g;f&&(f(),f=g);return a};a||(a=r.close);r.open=function(h,i){s.assert(h&&(h.constructor===String||h.constructor===HTMLDivElement));b&&r.close();document.g.classList.add("popup");
var l=document.createElement("div");l.id="popupClose";l.style.width="100%";l.style.textAlign="center";l.style.clear="both";var k=document.createElement("div");k.style.display="inline-block";k.style.cursor="pointer";var n=document.createElementNS("http://www.w3.org/2000/svg","svg");n.setAttributeNS(o,"width","24px");n.setAttributeNS(o,"height","24px");n.setAttributeNS(o,"style","inline-block;cursor: pointer");var j=document.createElementNS("http://www.w3.org/2000/svg","line");j.setAttributeNS(o,"x1",
0);j.setAttributeNS(o,"y1",0);j.setAttributeNS(o,"x2",24);j.setAttributeNS(o,"y2",24);j.setAttributeNS(o,"stroke-width","2");j.setAttributeNS(o,"style","inline-block;cursor: pointer");n.appendChild(j);j=document.createElementNS("http://www.w3.org/2000/svg","line");j.setAttributeNS(o,"x1",24);j.setAttributeNS(o,"y1",0);j.setAttributeNS(o,"x2",0);j.setAttributeNS(o,"y2",24);j.setAttributeNS(o,"stroke-width","2");j.setAttributeNS(o,"style","inline-block;cursor: pointer");n.appendChild(j);k.appendChild(n);
n=document.createElement("div");n.style.cursor="pointer";n.style.lineHeight="5px";n.innerHTML="<span style='font-size: 75%;cursor:pointer'>close</span><style>#popupClose svg{stroke: white}</style>";k.appendChild(n);b=document.createElement("div");b.id="popup";b.style.position="absolute";b.style.zIndex="10001";h.constructor===String?b.innerHTML=h:b.appendChild(h);l.appendChild(k);b.appendChild(l);b.o();document.g.appendChild(b);if(!b.K())return r.close(),setTimeout(function(){arguments.callee(arguments[0],
arguments[1],arguments[2],arguments[3])},100),q;document.querySelector("#popupClose *").onclick=a;c();b.show();f=i;e=document.createElement("div");e.id="overlay";e.style.position="fixed";e.style.height="100%";e.style.width="100%";e.style.top="0";e.style.left="0";e.style.zIndex=parseInt(b.style.zIndex,10)-1;e.onclick=a;document.g.appendChild(e);var p=parseInt(b.a("width"),10),t=parseInt(b.a("height"),10);s.assert(!d);d=window.setInterval(function(){var a=parseInt(b.a("width"),10),e=parseInt(b.a("height"),
10);if(a!=p||e!=t)c(),p=a,t=e},100);return m};r.U=function(b){a=b};r.za=c;window.addEventListener("resize",c,q);return r};s.F=function(a){var c=o;a.target?c=a.target:a.srcElement&&(c=a.srcElement);3==c.nodeType&&(c=c.parentNode);return c};s.oa=function(a,c){s.assert(a.parentElement!==g);do if(a===c)return m;while(a=a.parentElement);return q};s.C=function(a){if("keypress"===a.type){var c={10:"enter",13:"enter",32:" ",37:"left",38:"up",39:"right",40:"down",43:"+",45:"-",47:"/",48:"0",49:"1",50:"2",
51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",63:"?",65:"A",66:"B",67:"C",68:"D",69:"E",70:"F",71:"G",72:"H",73:"I",74:"J",75:"K",76:"L",77:"M",78:"N",79:"O",80:"P",81:"Q",82:"R",83:"S",84:"T",85:"U",86:"V",87:"W",88:"X",89:"Y",90:"Z",97:"a",98:"b",99:"c",100:"d",101:"e",102:"f",103:"g",104:"h",105:"i",106:"j",107:"k",108:"l",109:"m",110:"n",111:"o",112:"p",113:"q",114:"r",115:"s",116:"t",117:"u",118:"v",119:"w",120:"x",121:"y",122:"z",666:"comma dummy"};if(a.i)return c[a.i];if(0===a.charCode)return c[a.keyCode];
s.assert(a.charCode);return c[a.charCode]}if("keydown"===a.type||"keyup"===a.type||"change"===a.type)return c={13:"enter",27:"esc",32:" ",37:"left",38:"up",39:"right",40:"down",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",
187:"+",189:"-",666:"comma dummy"},a.i?c[a.i]:c[a.keyCode];s.assert(q)};(function(){if(!Element.prototype.hasOwnProperty("classList")){var a=/^\s+|\s+$/g,c=function(a,b){if(""===b)throw"SYNTAX_ERR";if(/\s/.test(b))throw s.assert(q),"INVALID_CHARACTER_ERR";return a.indexOf(b)},b=function(){var b=this,d=b.className.replace(a,"").split(/\s+/);return{length:d.length,item:function(a){return d[a]||o},contains:function(a){return-1!==c(d,a)},add:function(a){-1===c(d,a)&&(d.push(a),this.length=d.length,b.className=
d.join(" "))},remove:function(a){a=c(d,a);-1!==a&&(d.splice(a,1),this.length=d.length,b.className=d.join(" "))},toggle:function(a){-1===c(d,a)?this.add(a):this.remove(a)},toString:function(){return b.className}}};Object.defineProperty?Object.defineProperty(Element.prototype,"classList",{get:b}):Object.prototype.__defineGetter__&&Element.prototype.__defineGetter__("classList",b)}})();s.S=function(){var a={},c=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||
window.msRequestAnimationFrame,b=window.cancelRequestAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame;return!c||!b?function(a){a()}:function(e){a[e]&&b(a[e]);a[e]=c(e)}}();s.l=function(a,c,b,e,d){s.assert("key"!=a);if(b===g||b===o)b="";var f=document.getElementById(a);if(window.localStorage!==g){s.l.w||function(){if(window.localStorage.key){for(var a={},b=0;b<window.localStorage.length;b++)a[window.localStorage.key(b)]=
m;for(var c in a)window.localStorage[c]||(window.localStorage[c]="");s.l.w=m}}();var h=b===q||b===m,b=window.localStorage.getItem(a)!==o?window.localStorage[a]:b;h&&(b=!!b);s.assert(h===("checkbox"===f.type));"SELECT"===f.nodeName&&0===f.childNodes.length&&(f.innerHTML="<option>"+b+"</option>");f[h?"checked":"value"]=b;c&&!d&&c(b);var i,d=function(){i&&window.clearTimeout(i);i=window.setTimeout(function(){var b=h?f.checked?"true":"":f.value;window.localStorage[a]!=b&&(window.localStorage[a]=b,c&&
c(h?!!b:b))},e!==g?e:h?0:1E3)};(h||"SELECT"===f.nodeName)&&f.addEventListener("change",d,q);(!h||"SELECT"===f.nodeName)&&f.addEventListener("keyup",d,q)}else f.parentNode.removeChild(f),d||c(b)};s.la=function(a,c,b){function e(){f.style.backgroundColor=i;f.style.backgroundImage=l}function d(a){if(-1!==a.indexOf(".")||/^data:image/.test(a)){var b=document.createElement("img"),c;b.onload=function(){var a=this.width,b=this.height;4E6<a*b?alert("The provided image has a size of "+a+"*"+b+" pixels. Large images are likely to slow down your machine. Thus only images of maximal 4 000 000 pixels -- e.g. 2500*1600 pixels -- are allowed."):
e();c=m};b.onerror=function(){l===h&&(l="none",e())};window.setTimeout(function(){!c&&l==='url("'+a+'")'&&(i="",l=h,e(),i="",l='url("'+a+'")')},50);i="";l='url("'+a+'")';b.src=a}else""===a||-1!==a.indexOf("gradient")?(i="",l=""===a?"none":a):(i=a,l="none"),e()}s.assert(!arguments.callee.P);arguments.callee.P=m;var f=document.documentElement,h="url(http://slimpic.com/images/loading.gif)";f.style.backgroundSize="cover";f.style.backgroundAttachment="fixed !important";var i,l;s.e().h?c.X():s.l(a,d,b);
return d};s.ha=function(a,c,b,e){var d,f;(function(){function b(){location.hash==="#"+e?(document.documentElement.webkitRequestFullScreen&&document.documentElement.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT),document.documentElement.mozRequestFullScreen&&document.documentElement.mozRequestFullScreen()):(document.webkitCancelFullScreen&&document.webkitCancelFullScreen(),document.mozCancelFullScreen&&document.mozCancelFullScreen())}var e="fullscreen";d=function(){location.hash=location.hash===
"#"+e?"":e;b()};(function(){var d,h;f=function(){s.S(function(){if(!h||h!=d)b(),h=d;location.hash==="#"+e?(a(),d=m):(c(),d=q)})}})()})();for(var h=0;h<b.length;h++)b[h].addEventListener("click",d,q);e&&window.addEventListener("keydown",function(a){a=a||window.event;if(!s.J(a)){var b=s.F(a).type;"text"===b||"url"===b||s.C(a)===e&&d()}},q);f();s.m(f);window.addEventListener("resize",function(){setTimeout(f,1)},q);return f};s.N=function(a){s.assert(a.constructor===Array);for(var c={},b=0;b<a.length;b++){var e=
a[b];c[e]?a.splice(b--,1):c[e]=m}return a};s.ma=function(){if(!arguments.length)return[];for(var a=arguments[0],c=a2=o,b=1;b<arguments.length;){c=[];a2=arguments[b];for(var e=a.length,d=a2.length,f=0;f<e;f++)for(var h=0;h<d;h++)a[f]===a2[h]&&c.push(a[f]);a=c;b++}return s.N(a)};s.ta=function(a){s.assert(a.constructor===Object);var c=0,b;for(b in a)a.hasOwnProperty(b)&&c++;return c};(function(){var a={};s.D=function(c){a[c]||(a[c]=document.getElementById(c));return a[c]};window.$=s.D})();(function(){try{window.btoa("\u8bed\u0e01\u01f5")}catch(a){var c=
{f:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",B:function(a){for(var e="",d,f,h,i,j,k,n=0,a=c.t(a);n<a.length;)d=a.charCodeAt(n++),f=a.charCodeAt(n++),h=a.charCodeAt(n++),i=d>>2,d=(d&3)<<4|f>>4,j=(f&15)<<2|h>>6,k=h&63,isNaN(f)?j=k=64:isNaN(h)&&(k=64),e=e+this.f.charAt(i)+this.f.charAt(d)+this.f.charAt(j)+this.f.charAt(k);return e},A:function(a){for(var e="",d,f,h,i,j,k=0,a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<a.length;)d=this.f.indexOf(a.charAt(k++)),f=this.f.indexOf(a.charAt(k++)),
i=this.f.indexOf(a.charAt(k++)),j=this.f.indexOf(a.charAt(k++)),d=d<<2|f>>4,f=(f&15)<<4|i>>2,h=(i&3)<<6|j,e+=String.fromCharCode(d),64!=i&&(e+=String.fromCharCode(f)),64!=j&&(e+=String.fromCharCode(h));return e=c.s(e)},t:function(a){for(var a=a.replace(/\r\n/g,"\n"),c="",d=0;d<a.length;d++){var f=a.charCodeAt(d);128>f?c+=String.fromCharCode(f):(127<f&&2048>f?c+=String.fromCharCode(f>>6|192):(c+=String.fromCharCode(f>>12|224),c+=String.fromCharCode(f>>6&63|128)),c+=String.fromCharCode(f&63|128))}return c},
s:function(a){for(var c="",d=0,f=c1=c2=0;d<a.length;)f=a.charCodeAt(d),128>f?(c+=String.fromCharCode(f),d++):191<f&&224>f?(c2=a.charCodeAt(d+1),c+=String.fromCharCode((f&31)<<6|c2&63),d+=2):(c2=a.charCodeAt(d+1),c3=a.charCodeAt(d+2),c+=String.fromCharCode((f&15)<<12|(c2&63)<<6|c3&63),d+=3);return c}};window.btoa=c.B;window.atob=c.A}})();"Gecko"==window.navigator.product&&document.documentElement.removeAttribute("manifest")}})();window.O||(window.O={});
s.Y=function(t,w,x,v){function p(a,b){for(var b=b?[b]:[],e=document.getElementsByTagName("iframe"),d=0,f=e.length;d<f;d++)(e[d].id==t.id||e[d].parentNode.id==t.id)&&window.frames[d].postMessage(JSON.stringify({event:"command",func:a,args:b,id:1}),"*")}if(!t||!window.frames[0].postMessage)return q;var j={state:-1},r,a;window.addEventListener("message",function(c){if(c&&c.origin&&"http://www.youtube.com"===c.origin&&c.data){c=JSON.parse(c.data);if(c.info){var b=c.info.playerState;b!==g&&b!==o&&(j.state=
b,c.event&&"onStateChange"===c.event&&w&&w(b));var e;c.info.videoData&&(b=c.info.videoData.video_id,r!==b&&(r=b,e=m));b=c.info.videoBytesTotal;b!==g&&b!==a&&(b<a&&(e=m),a=b);e&&x()}v&&c.event&&"onError"===c.event&&v(c.error)}},q);t.onload=function(){j.state=!/youtube/.test(t.src)?-1:-2;j.V()};j.xa=function(){p("mute")};j.Ha=function(){p("unMute")};j.pause=function(){p("pauseVideo")};j.play=function(){p("playVideo")};j.Aa=function(a){p("seekTo",[a])};j.V=function(){p("setPlaybackQuality","default")};
j.Ca=function(a){p("setVolume",a)};return j};var u=document.getElementById("text");document.body.onload=function(){y();u.focus()};var z=m;window.onkeydown=function(){u.focus();z&&(document.getElementById("hint").style.opacity="0",u.innerHTML=" ",z=q)};window.onfocus=function(){u.focus()};function y(){u.W();u.style.marginTop="0px";u.style.marginTop=window.innerHeight/2-u.n().y-parseInt(u.a("height"))/2+"px"}u.onkeyup=function(){y()};window.onresize=y;

});

})();
